# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys

oem: "TECNO"
product: "KH7n-RU"
device: "TECNO-KH7n"
android_version: "12"
build_tag: "SP1A.210812.016"
incremental: "231212V1593"
model: "TECNO SPARK 9 Pro"
