name: google-ota

on:
 workflow_dispatch:
   inputs:
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'Tecno Spark 9 Pro'
      CODE_NAME:
        description: 'CODE_NAME'
        required: true
        default: 'TECNO-KH7n'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Prepare the environment
      run: |
        sudo apt -y install python2 python3
        pip install pyyaml requests protobuf

    - name: Clone repo
      run: |
        git clone https://github.com/isus203/google-ota-prober
        cd google-ota-prober
        
    - name: Search ota
      run: |
        python probe.py --download

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.zip
        name: ${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Device name: ${{ github.event.inputs.DEVICE_NAME }}
          Code name: ${{ github.event.inputs.CODE_NAME } 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
