name: google-ota

on:
 workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Prepare the environment
      run: |
        sudo apt -y install python2 python3
        pip install pyyaml requests protobuf

    - name: Clone repo
      run: |
        git clone https://github.com/isus203/google-ota-prober
        cd google-ota-prober
        
    - name: Search ota
      run: |
        python probe.py --download
        ls

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.zip
        name: ${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Target: *.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
