name: google-ota

on:
  workflow_dispatch:
    inputs:
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'Tecno Spark 9 Pro'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Prepare the environment
      run: |
        sudo apt -y install python2 python3
        pip install pyyaml requests protobuf

    - name: Clone repo
      run: |
        git clone https://github.com/isus203/google-ota-prober
        cd
        cd google-ota-prober
        
    - name: Search ota
      run: |
        python probe.py --download

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: | 
          google-ota-prober/*.zip
        name: ${{ github.event.inputs.DEVICE_NAME }}
        body: |
          Device: ${{ github.event.inputs.DEVICE_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
