name: google-ota

on:
  workflow_dispatch:
    inputs:
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'Tecno Spark 9 Pro'
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true
        default: 'https://github.com/isus203/google-ota-prober'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install python2 python3
      
    - name: Clone repo
      run: |
        mkdir workspace
        cd workspace
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }}
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT 

    - name: Installing dependency 
      run: |
        pip install pyyaml requests protobuf

    - name: Search ota
      run: |
        python probe.py --download

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: | 
          workspace/google-ota-prober/*.zip
        name: ${{ github.event.inputs.DEVICE_NAME }}
        body: |
          Device: ${{ github.event.inputs.DEVICE_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
